# Generated by Django 3.2.9 on 2022-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, '温度'), (2, '湿度')], verbose_name='種別')),
                ('value', models.FloatField(verbose_name='計測内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '計測値',
                'db_table': 'measurement',
            },
        ),
    ]
